config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }


  Plezi.route '/ws', ChatServer


  devise_scope :user do
    post 'signup/send_sms' => 'users/registrations#send_sms'
  end

  get '/valid/:attr' => 'validations#valid'

  post '/chatroom/request_addr' => 'chatroom#request_addr'

  get 'basketball' => 'home#basketball', as: :basketball
  get 'baseball' => 'home#baseball', as: :baseball
  get 'soccer' => 'home#soccer', as: :soccer

  namespace :admin do
    resources :users
    
    root to: 'home#index'
  end

  root to: 'home#index'
end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/views/admin/admin_users/_form.html.slim
= simple_nested_form_for @admin_user, url: url, html: { class: 'horizontal_form' } do |f|
  .normal-tools.clearfix
    .fr.action
      = f.button :submit, '保存', class: 'btn-primary'
      a.btn.btn-secondary href=''  取消
    .fl.s-title= @admin_user.new_record? ? '添加管理员' : '编辑管理员'
  .container
    fieldset
      legend 基本信息

      .clearfix.normal-form
        = f.input :name
        = f.input :email
        = f.input :password
        = f.input :password_confirmation
  .mt20
  .normal-tools.clearfix
    .fr.action
      = f.button :submit, '保存', class: 'btn-primary'
      a.btn.btn-secondary href=""  取消

app/views/admin/admin_users/edit.html.slim
= render 'form', url: admin_admin_user_path(@admin_user)

app/views/admin/admin_users/index.html.slim
.normal-tools.clearfix
  .fr.action= link_to '添加管理员', new_admin_admin_user_path, class: 'btn btn-secondary'
  .fl.s-title
    = t("views.admin.#{@main_nav}")
    = '-'
    = t("views.admin.#{@sec_nav}")

.main
  .w20.fl
    .side-bar
      .default-title 搜索
      = search_form_for @q, builder: SimpleForm::FormBuilder, url: admin_admin_users_path, html: { class: 'form-horizontal stockins-search mt20' } do |f|
        = f.input :name_cont, wrapper: :side_search, placeholder: '搜名字'
        = f.input :email_cont, wrapper: :side_search, placeholder: '搜邮箱'
        = f.button :submit, '搜一搜', class: 'btn-primary'
        = link_to '重置搜索', admin_categories_path, class: 'btn btn-secondary ml10'


  .w80.fl
    table.table.table-hover.bbe
      tr
        th= AdminUser.human_attribute_name(:id)
        th= AdminUser.human_attribute_name(:name)
        th= AdminUser.human_attribute_name(:email)
        th= AdminUser.human_attribute_name(:sign_in_count)
        th= AdminUser.human_attribute_name(:last_sign_in_at)
        th= AdminUser.human_attribute_name(:last_sign_in_ip)
        th= AdminUser.human_attribute_name(:created_at)
        th
      tr
        td.h2 colspan='3'
      - @admin_users.each do |resource|
        tr
          td= resource.id
          td= resource.name
          td= resource.email
          td= resource.sign_in_count
          td
            - if resource.last_sign_in_at.present?
              = l resource.last_sign_in_at, format: :long

          td= resource.last_sign_in_ip
          td= l resource.created_at, format: :long
          td
            .fl.btn-group.tools-group
              a.btn.btn-sm.btn-secondary.dropdown-toggle href="" data-toggle="dropdown" ...
              .dropdown-menu
                ul.menu-list
                  li= link_to '编辑', edit_admin_admin_user_path(resource)
                  li= link_to '删除', admin_admin_user_path(resource), method: :delete, data: { confirm: Settings.notices.delete_confirm }

    .table-total 共计: #{ @admin_users.count }个

app/views/admin/admin_users/new.html.slim
= render 'form', url: admin_admin_users_path