config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }


  Plezi.route '/ws', ChatServer


  devise_scope :user do
    post 'signup/send_sms' => 'users/registrations#send_sms'
  end

  get '/valid/:attr' => 'validations#valid'

  post '/chatroom/request_addr' => 'chatroom#request_addr'

  get 'basketball' => 'home#basketball', as: :basketball
  get 'baseball' => 'home#baseball', as: :baseball
  get 'soccer' => 'home#soccer', as: :soccer

  namespace :admin do
    resources :users
    
    root to: 'home#index'
  end

  root to: 'home#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout proc { |controller| controller.request.xhr? ? false : 'application' }

  before_action :get_user

  def get_user
    if @chatroom == true
      if user_signed_in?
        user = current_user

        cookies[:uid] = user.uid
        cookies[:sdktoken] = user.token
        cookies[:nickName] = user.name
      else
        # user = User.find_by mobile_phone: '18600000000'
        uid = User.first._gen_uid_value
        NeteaseIM::User.create(accid: uid.to_s, name: "游客#{uid}", token: token.to_s)
        token = uid

        cookies[:uid] = uid
        cookies[:sdktoken] = token
        cookies[:nickName] = nil
      end

      cookies[:roomid] = Chatroom::ROOMID
    end
  end

  class << self
    def main_nav_highlight(name)
      before_action { |c| c.instance_variable_set(:@main_nav, name) }
    end

    def sec_nav_highlight(name)
      before_action { |c| c.instance_variable_set(:@sec_nav, name) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def main_nav(name, options = {}, &block)
    if @main_nav == name
      if options[:class]
        options[:class] += ' active'
      else
        options[:class] = 'active'
      end
    end
    content = capture(&block)
    content_tag(:li, content, options)
  end

  def sec_nav(name, options = {}, &block)
    if @sec_nav == name
      if options[:class]
        options[:class] += ' active'
      else
        options[:class] = 'active'
      end
    end
    content = capture(&block)
    content_tag(:li, content, options)
  end
  
end

app/views/application/_chatroom.html.slim
.main.cf.pt20.pb20.m-room#room
  .fl.w800
    #leisu-free.leisu-free
  .fr.w270
    .discussion
      .m-status#linkStatus.hide 连接中。。。
      .announcement_title 直播公告
      .announcement#roomAnnouncement
      ul.tab.cf
        li.crt.j-tab.fl data-value="chat" 直播互动
        li.g-hide.j-tab.fr data-value="member"
          | 在线成员
          span#roomOnlineMemberNum
      .chat.j-pannel.j-chat#output
      .member.j-pannel.hide
        .list.j-member
        .more.j-more
          a 加载更多
      .edit
        form#monitor
          p
            input#input placeholder="Your message" type="text"
            input type="submit" value="Broadcast"
          ul#output

        / textarea.editText#editText placeholder="Ctrl+Enter快速发送"
      .sendBtn.cf
        #emojiTag
        a#sentText.u-btn.btn 发送
        a#customBtn.btn.custom
        a#emoji.btn.emoji

    #menu.m-menu.hide
      ul
        li.j-item.j-kick data-type="0"  title="移除直播室" 踢人
        li.j-item.j-gag data-type="1" title="禁止发言" 禁言
        li.j-item.j-black data-type="2"  title="永久不能进入该直播间" 拉黑该用户
        li.j-item.admin.j-admin data-type="3" 任命管理员

- content_for :js do
  coffee:
    $('#monitor')[0].onsubmit = send_text

app/views/application/_foot.html.slim
.footer-wrap
  .main
    .footer
      a.white href="" 沪 ICP 备 xxxxxx 号-1
      span="|"
      | Copyright © 2015-2016 xxxx.ALL Rights Reserved
      span="|"
      a.white href="" 关于xx
      span="|"
      a.white href="" 免责声明
      span="|"
      a.white href="" 网站地图
      span="|"
      a.white href="" 联系方式
      span="|"
      a.yellow href="" 免费比分调用

app/views/application/_header.html.slim
.h60
  .header-wrap
    .main.cf
      a.logo.fl href=""
        img data-src="holder.js/113x32" alt=""/
      ul.head-nav.fl
        = main_nav :home do
          = link_to '足球比分', root_path
        = main_nav :basketball do
          = link_to '篮球比分', basketball_path
        = main_nav :baseball do
          = link_to '棒球比分', baseball_path
        = main_nav :soccer do
          = link_to '美式足球比分', soccer_path
        li
          a href="" 收藏本站
        li
          a target='_blank' href='https://static.meiqia.com/dist/standalone.html?_=t&eid=74298' 联系我们
      .login-wrap.fr
        - if user_signed_in?
          = link_to '退出登录', destroy_user_session_path, class: 'btn btn-white', method: :delete
        - else
          i.iconfont.red &#xe652;
          a.btn.btn-white.js-login-link.ajax-popup data-type='ajax' href='javascript:void(0);' data-src=new_user_session_path 登录
          a.btn.btn-red href=new_user_registration_path 注册

app/views/application/_kefu.html.erb
<script type='text/javascript'>
  (function(m, ei, q, i, a, j, s) {
    m[i] = m[i] || function() {
      (m[i].a = m[i].a || []).push(arguments)
    };
    j = ei.createElement(q),
      s = ei.getElementsByTagName(q)[0];
    j.async = true;
    j.charset = 'UTF-8';
    j.src = 'https://static.meiqia.com/dist/meiqia.js?_=t';
    s.parentNode.insertBefore(j, s);
  })(window, document, 'script', '_MEIQIA');
  _MEIQIA('entId', 74298);
</script>