config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }


  Plezi.route '/ws', ChatServer


  devise_scope :user do
    post 'signup/send_sms' => 'users/registrations#send_sms'
  end

  get '/valid/:attr' => 'validations#valid'

  post '/chatroom/request_addr' => 'chatroom#request_addr'

  get 'basketball' => 'home#basketball', as: :basketball
  get 'baseball' => 'home#baseball', as: :baseball
  get 'soccer' => 'home#soccer', as: :soccer

  namespace :admin do
    resources :users
    
    root to: 'home#index'
  end

  root to: 'home#index'
end

app/views/layouts/admin.html.slim
doctype html
html
  head
    title HG

    meta content='width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0' name='viewport'
    meta content='telephone=no' name='format-detection'

    = stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'admin', 'data-turbolinks-track': 'reload'
    
    = csrf_meta_tags
    = favicon_link_tag '/favicon.png', type: 'image/png'

  body
    - if admin_user_signed_in?
      = render '/admin/shared/header'
      = render '/admin/shared/message'

    = yield

    = yield :js

app/views/layouts/application.html.slim
doctype html
html
  head
    title hg

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'

    = csrf_meta_tags
    = favicon_link_tag '/favicon.png', type: 'image/png'

  body
    = render 'header'
    = render 'chatroom' if @main_nav

    = yield

    = render 'foot'

    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    = yield :js